import { baseURL } from '../app-config.service';
export const baseUrl = baseURL;

export enum UrlNames {
    GetStoreHome = 'Store/StoreGetHome',
    StoreGetDetail = 'Store/StoreGetDetail',
    StoreGetList = 'Store/StoreGetList',
    LoginCustomer = 'Login/LoginCustomer',
    ForgotPassword  = 'Login/ForgotPassword',
    ProductGetList = 'Product/ProductGetList',
    ProductGetDetails = 'Product/ProductGetDetail',
    EventGetDetails = 'Event/EventGetDetail',
    FavoriteProductUpdate = 'Product/FavoriteProductUpdate',
    RecipeGetList = 'Recipe/RecipeGetList',
    RecipeGetDetail = 'Recipe/RecipeGetDetail',
    CartAddItem = 'Cart/CartAddItem',
    CartRemoveItem = 'Cart/CartRemoveItem',
    CartGetDetail = 'Cart/CartGetDetail',
    ReviewGetList = 'Review/ReviewGetList',
    ReviewRatingInsert = 'Review/ReviewRatingInsert',
    ReviewRatingUpdate = 'Review/ReviewRatingUpdate',
    OrderGetList = 'Order/OrderGetList',
    OrderInsert = 'Cart/OrderInsert',
    OrderCancel = 'Order/OrderCancel',
    CartUpdate = 'Cart/CartUpdate',
    CustomerAddressGetList = 'Customer/CustomerAddressGetList',
    AddressInsert = 'Customer/AddressInsert',
    AddressDelete = 'Customer/AddressDelete',
    AddressUpdate = 'Customer/AddressUpdate',
    ProfileGetDetail = 'Customer/ProfileGetDetail',
    CustomerProfileUpdate = 'Customer/CustomerProfileUpdate',
    UploadImage = 'Customer/UploadImage',
    CustomerPaymentMethodGetList = 'Customer/CustomerGetPayMethods',
    CustomerPaymentInsert = 'Customer/CustomerPaymentInsert',
    CouponGetList = 'Coupon/CouponGetList',
    ReOrderCart = 'Cart/ReOrderCart',
    VantivRequestAndResponseInsert = 'Store/VantivRequestAndResponseInsert',
    VantivGetSetUpTransactionId = 'Customer/VantivGetSetUpTransactionId',
    VantivCardsGetList = 'Customer/VantivCardsGetList',
    VantivCardDelete = 'Customer/VantivCardDelete',
    VantivGetQueryDetails = 'Customer/VantivGetQueryDetails',
    VantivAddCard = 'Customer/VantivAddCard',
    VantivCardPayment = 'Customer/VantivCardPayment',
    VantivCardReversal = 'Customer/VantivCardReversal',
    StoreContactUs = 'Store/StoreContactUs'
}
